var deck1 = {
	"Arid Mesa":1,
	"Blood Crypt":1,
	"Bloodstained Mire":4,
	"Godless Shrine":1,
	"Overgrown Tomb":1,
	"Sacred Foundry":1,
	"Stomping Ground":1,
	"Verdant Catacombs":1,
	"Windswept Heath":4,
	"Wooded Foothills":2,
	"Death's Shadow":4,
	"Monastery Swiftspear":4,
	"Steppe Lynx":2,
	"Street Wraith":4,
	"Tarmogoyf":1,
	"Wild Nacatl":4,
	"Become Immense":3,
	"Gitaxian Probe":4,
	"Lightning Bolt":2,
	"Mutagenic Growth":4,
	"Temur Battle Rage":4,
	"Thoughtseize":3,
	"Mishra's Bauble":4
};

var deck2 = {
	"Breeding Pool":2,
	"Cinder Glade":1,
	"Forest":2,
	"Hallowed Fountain":1,
	"Island":3,
	"Misty Rainforest":4,
	"Mountain":1,
	"Plains":1,
	"Steam Vents":4,
	"Stomping Ground":4,
	"Temple Garden":1,
	"Valakut, the Molten Pinnacle":2,
	"Sakura-Tribe Elder":4,
	"Anger of the Gods":1,
	"Bring to Light":4,
	"Cryptic Command":3,
	"Electrolyze":1,
	"Farseek":2,
	"Hunting Wilds":1,
	"Izzet Charm":2,
	"Remand":4,
	"Scapeshift":3,
	"Search for Tomorrow":4,
	"Worldly Counsel":2,
	"Engineered Explosives":3
};